#!/usr/bin/env python3
"""Bake the existing Meta avatar into small ROM RGB565 frames; no runtime renderer."""
from pathlib import Path
import os
import shlex
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
# Each invocation resets the renderer's deterministic palette/eyes state.
FRAMES = [(1,128,t,0) for t in (.5,1.1,1.7,.08)]
FRAMES += [(2,128,.6,level) for level in (.05,.45,.9)]
FRAMES += [(3,128,t,0) for t in (.4,.8,1.2)]
FRAMES += [(5,128,t,0) for t in (.08,1)]
FRAMES += [(1,48,t,0) for t in (.5,1.1,1.7,.08)]
FRAMES += [(4,48,.6,level) for level in (.05,.45,.9)]
FRAMES += [(5,48,t,0) for t in (.08,1)]
C = r'''
#include <stdio.h>
#include <stdlib.h>
#include "muse_pixel.h"
int main(int argc,char **argv){
 if(argc!=5)return 1;
 int mode=atoi(argv[1]),size=atoi(argv[2]);float target=strtof(argv[3],0),level=strtof(argv[4],0);
 muse_pixel_set_size(size);
 muse_pose_t p={.mode=mode,.mode_t=2,.level=level};
 for(float t=0;t<target;t+=.04f){p.t=t;muse_pixel_render(&p);}
 p.t=target;muse_pixel_render(&p);
 uint16_t row[128];
 for(int y=0;y<size;y++){
  muse_pixel_scale(row,size,0,size-1,y,y);
  for(int x=0;x<size;x++){unsigned char b[2]={row[x]&255,row[x]>>8};if(fwrite(b,1,2,stdout)!=2)return 1;}
 }
 return 0;
}
'''

def generate():
    output = ROOT / 'components/muse'
    data = bytearray(); descriptors = []
    with tempfile.TemporaryDirectory() as tmp:
        source=Path(tmp)/'render.c';source.write_text(C);exe=Path(tmp)/'render'
        subprocess.run([*shlex.split(os.environ.get('CC','cc')), '-std=c11','-O2','-I',str(output),str(source),str(ROOT/'avatar/muse_pixel.c'),'-lm','-o',str(exe)],check=True)
        for mode,size,t,level in FRAMES:
            frame=subprocess.check_output([str(exe),str(mode),str(size),str(t),str(level)])
            assert len(frame)==size*size*2
            descriptors.append(f'    {{.header={{.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w={size},.h={size},.stride={size*2}}},.data_size={len(frame)},.data=avatar_data+{len(data)}}},')
            data.extend(frame)
    (output/'passport_avatar.rgb565').write_bytes(data)
    (output/'passport_avatar.c').write_text('''/* Copyright (c) Meta Platforms, Inc. and affiliates.
 * Derived from esp32/avatar/muse_pixel.c; its avatar license applies.
 * Generated by esp32/tools/gen_passport_avatar.py. Pixels remain in Flash. */
#include "passport_avatar.h"
extern const uint8_t avatar_data[] asm("_binary_passport_avatar_rgb565_start");
static const lv_image_dsc_t images[] = {
'''+'\n'.join(descriptors)+'''
};
const lv_image_dsc_t *passport_avatar_frame(muse_mode_t mode, bool small, unsigned tick, float level)
{
    /* Idle spends most time awake, with one brief blink every four seconds. */
    unsigned idle = tick % 40 == 39 ? 3 : (tick / 8) % 3;
    unsigned volume = level > .6f ? 2 : level > .18f ? 1 : 0;
    if (small) {
        if (mode == MUSE_MODE_SPEAKING) return &images[16 + volume];
        if (mode == MUSE_MODE_ERROR) return &images[19 + (tick / 4) % 2];
        return &images[12 + idle];
    }
    if (mode == MUSE_MODE_LISTENING) return &images[4 + volume];
    if (mode == MUSE_MODE_THINKING) return &images[7 + (tick / 3) % 3];
    if (mode == MUSE_MODE_ERROR) return &images[10 + (tick / 4) % 2];
    return &images[idle];
}
''')
    print(f'{len(FRAMES)} frames, {len(data)} bytes in Flash')

if __name__=='__main__': generate()
