/* Copyright (c) Meta Platforms, Inc. and affiliates.
 * Derived from esp32/avatar/muse_pixel.c; its avatar license applies.
 * Generated by esp32/tools/gen_passport_avatar.py. Pixels remain in Flash. */
#include "passport_avatar.h"
extern const uint8_t avatar_data[] asm("_binary_passport_avatar_rgb565_start");
static const lv_image_dsc_t images[] = {
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+0},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+32768},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+65536},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+98304},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+131072},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+163840},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+196608},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+229376},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+262144},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+294912},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+327680},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=128,.h=128,.stride=256},.data_size=32768,.data=avatar_data+360448},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=48,.h=48,.stride=96},.data_size=4608,.data=avatar_data+393216},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=48,.h=48,.stride=96},.data_size=4608,.data=avatar_data+397824},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=48,.h=48,.stride=96},.data_size=4608,.data=avatar_data+402432},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=48,.h=48,.stride=96},.data_size=4608,.data=avatar_data+407040},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=48,.h=48,.stride=96},.data_size=4608,.data=avatar_data+411648},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=48,.h=48,.stride=96},.data_size=4608,.data=avatar_data+416256},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=48,.h=48,.stride=96},.data_size=4608,.data=avatar_data+420864},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=48,.h=48,.stride=96},.data_size=4608,.data=avatar_data+425472},
    {.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=48,.h=48,.stride=96},.data_size=4608,.data=avatar_data+430080},
};
const lv_image_dsc_t *passport_avatar_frame(muse_mode_t mode, bool small, unsigned tick, float level)
{
    /* Idle spends most time awake, with one brief blink every four seconds. */
    unsigned idle = tick % 40 == 39 ? 3 : (tick / 8) % 3;
    unsigned volume = level > .6f ? 2 : level > .18f ? 1 : 0;
    if (small) {
        if (mode == MUSE_MODE_SPEAKING) return &images[16 + volume];
        if (mode == MUSE_MODE_ERROR) return &images[19 + (tick / 4) % 2];
        return &images[12 + idle];
    }
    if (mode == MUSE_MODE_LISTENING) return &images[4 + volume];
    if (mode == MUSE_MODE_THINKING) return &images[7 + (tick / 3) % 3];
    if (mode == MUSE_MODE_ERROR) return &images[10 + (tick / 4) % 2];
    return &images[idle];
}
